# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtoc < Formula
  desc "Go-based Markdown Table of Contents manager with numbering and stable anchor links."
  homepage "https://github.com/rokath/mdtoc"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rokath/mdtoc/releases/download/v0.1.7/mdtoc_darwin_amd64.tar.gz"
      sha256 "1fbcf7a40d3a1425fe193a58a012b646753ebe9eb39ffa5374a8e9a44cdffa7d"

      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rokath/mdtoc/releases/download/v0.1.7/mdtoc_darwin_arm64.tar.gz"
      sha256 "0579a05c5ed833b7297bc7709a15e02761ef31cb4cb71c86a63b8fbf776d470b"

      define_method(:install) do
        bin.install "mdtoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.1.7/mdtoc_linux_amd64.tar.gz"
      sha256 "d24784ea6106246e83bc38a6966673f5406e139a2d8732556e6f6a929a0a1ed4"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.1.7/mdtoc_linux_arm6.tar.gz"
      sha256 "6aecb80eb469d49aee7325d0d3c2a9f4217503d9e15628b25e8ca96c6d46f740"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.1.7/mdtoc_linux_arm64.tar.gz"
      sha256 "ada0b75b2bed9d56ca4976fe030bc7bf1f4249ae087be2576cd42a32dd8d43a7"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
  end

  test do
    system "#{bin}/mdtoc", "--version"
  end
end
