# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtoc < Formula
  desc "Go-based Markdown Table of Contents manager with numbering and stable anchor links."
  homepage "https://github.com/rokath/mdtoc"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.3/mdtoc_darwin_amd64.tar.gz"
      sha256 "a56f5df7b7db261c91afadab846c5fedf39f4c03d8ecf3abebc54eab32636973"

      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.3/mdtoc_darwin_arm64.tar.gz"
      sha256 "ab6c9b6caa9758170df8262fb9fe97617d99e617dfb7c44865fe76d64136e690"

      define_method(:install) do
        bin.install "mdtoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.3/mdtoc_linux_amd64.tar.gz"
      sha256 "5db262f59f34316dda07f14ffe9ed1f96da5b7f396023df7bc5cf0bc6758c935"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.3/mdtoc_linux_arm6.tar.gz"
      sha256 "7400e4af43ea722893e4854f762c9d632a05cb272ec245583139cd39efd18ff0"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.3/mdtoc_linux_arm64.tar.gz"
      sha256 "3577ed03e679a8e686f72cf109737b01855489d74f9f486171f36e59c7b004b4"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
  end

  test do
    system "#{bin}/mdtoc", "--version"
  end
end
