# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtoc < Formula
  desc "Go-based Markdown Table of Contents manager with numbering and stable anchor links."
  homepage "https://github.com/rokath/mdtoc"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.0/mdtoc_darwin_amd64.tar.gz"
      sha256 "f39ad5a7fa68139fbc65612970eb50b609c31e29abfd8fc298bcdc4e5b32a525"

      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.0/mdtoc_darwin_arm64.tar.gz"
      sha256 "f7335a525393f181979601ead237acf8830caba3ead57ab38b283e66be3c03e4"

      define_method(:install) do
        bin.install "mdtoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.0/mdtoc_linux_amd64.tar.gz"
      sha256 "0cb2583d60470c10d58dc3b9e8e7f5eddaaad3020c7f00837de817192e5b2ba2"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.0/mdtoc_linux_arm6.tar.gz"
      sha256 "2627e7d01d7bb66d8a6060d5ae6f5b813a92ddc03c88ccf1e6705e17af4273ae"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rokath/mdtoc/releases/download/v0.3.0/mdtoc_linux_arm64.tar.gz"
      sha256 "1e95bbc76c280a53bbf3b496f1ccc4c003ce508be67de4aaadafbd7acfc123e3"
      define_method(:install) do
        bin.install "mdtoc"
      end
    end
  end

  test do
    system "#{bin}/mdtoc", "--version"
  end
end
